jenkins-x/go-scm

scm/driver/stash/pr.go

This is a first spike at implementing ListComments for Bitbucket Server PRs

feat: implement stash.PullRequestService.ListComments

---

scm/factory/examples/repos/main.go

Getting my feet wet in the scm project as a prelude to tackling real issues

fix: typos in sample program

---

scm/driver/github/testdata/webhooks/installation.json
scm/driver/github/testdata/webhooks/installation.json.golden
scm/driver/github/testdata/webhooks/installation_delete.json
scm/driver/github/testdata/webhooks/installation_delete.json.golden
scm/driver/github/webhook.go
scm/driver/github/webhook_test.go
scm/webhook.go

also added AppID for handling GitHub App install/uninstall webhooks

fix: missing installation ID

---

scm/app.go
scm/driver/github/app.go

Signed-off-by: warrenbailey <warren@warrenbailey.net>

feat: add function to get installations for an organisation

---

scm/driver/fake/pr.go

This was fine for Github, but not Gitlab.

fix: Switch PR comments to be stored separately from issue comments.

---

jenkins-x.yml

This adds a minimal PR build pipeline, which just runs `make test` to run the unit tests.

feat(tests): add PR build tests

---

OWNERS
scm/driver/fake/data.go
scm/driver/fake/pr.go

Ran into problems with this trying to get Lighthouse updated.

chore: Fake PR apis should behave like fake issue APIs

---

scm/content.go
scm/driver/bitbucket/content.go
scm/driver/gitea/content.go
scm/driver/github/content.go
scm/driver/github/content_test.go
scm/driver/github/testdata/content_list.json
scm/driver/github/testdata/content_list.json.golden
scm/driver/gitlab/content.go
scm/driver/gogs/content.go
scm/driver/stash/content.go
scm/factory/examples/contentlist/main.go
scm/factory/examples/contents/main.go

so we can query contents in a directory and then fetch the contents for a file etc

fix: add an API for listing files in a repository

---

scm/driver/github/webhook.go

Signed-off-by: Cai Cooper <caicooper82@gmail.com>

chore: log HMAC token if debug is enabled

---

scm/driver/fake/org.go

this is needed as we want to mock List for https://github.com/cloudbees/jxui-backend/issues/444

feat: mock for github org list

---

scm/driver/github/org.go
scm/driver/gitlab/pr.go
scm/driver/gitlab/testdata/merge.json.golden
scm/driver/gitlab/testdata/merges.json.golden
scm/driver/gitlab/testdata/pr_create.json.golden
scm/pr.go

fix: Add mergeable/mergeable state handling for GitLab

---

scm/driver/github/webhook.go
scm/driver/github/webhook_test.go
scm/review.go
scm/webhook.go

chore: Add some more GitHub hooks

---

scm/driver/bitbucket/pr.go
scm/driver/fake/pr.go
scm/driver/gitea/pr.go
scm/driver/gitea/pr_test.go
scm/driver/github/pr.go
scm/driver/github/pr_test.go
scm/driver/github/testdata/pr_merge.json
scm/driver/github/util.go
scm/driver/gitlab/pr.go
scm/driver/gitlab/pr_test.go
scm/driver/gogs/pr.go
scm/driver/gogs/pr_test.go
scm/driver/stash/pr.go
scm/driver/stash/pr_test.go
scm/example_test.go
scm/pr.go

fix: Allow specifying GitHub merge method

---

scm/driver/bitbucket/org.go
scm/driver/fake/org.go
scm/driver/gitea/org.go
scm/driver/github/org.go
scm/driver/github/org_test.go
scm/driver/github/testdata/membership_admin.json
scm/driver/github/testdata/membership_member.json
scm/driver/gitlab/org.go
scm/driver/gogs/org.go
scm/driver/stash/org.go
scm/org.go

We want to be able to know if a given user is admin for a given org

feat: add isAdmin method to org api for github

---

jenkins-x.yml
scm/driver/gitlab/integration/content_test.go
scm/driver/gitlab/integration/issue_test.go
scm/driver/gitlab/integration/pr_test.go

chore: Run integration tests for GL and GH in PR build

---

scm/driver/bitbucket/org.go
scm/driver/fake/org.go
scm/driver/gitea/org.go
scm/driver/github/org.go
scm/driver/github/org_test.go
scm/driver/github/testdata/org_members.json
scm/driver/github/testdata/org_members.json.golden
scm/driver/gitlab/org.go
scm/driver/gogs/org.go
scm/driver/stash/org.go
scm/org.go

Very basic for the moment, but needed for https://github.com/jenkins-x/lighthouse/issues/675

feat: Add listing org members

---

scm/driver/github/org.go
scm/driver/github/org_test.go
scm/driver/github/repo.go
scm/driver/github/repo_test.go

fix: Handle GitHub IsMember/IsCollaborator 404s properly

---

scm/const.go
scm/driver/gitlab/integration/pr_test.go
scm/driver/gitlab/pr_test.go
scm/driver/gitlab/testdata/merges.json
scm/driver/gitlab/testdata/merges.json.golden
scm/driver/gitlab/util.go
scm/pr.go

We're going to need this for getting Lighthouse merging PRs to work properly.

feat: Add labels and update/create times to GitLab PR listing

---

scm/driver/bitbucket/repo.go
scm/driver/bitbucket/repo_test.go
scm/driver/bitbucket/testdata/status_input.json

chore: Add name field to BitBucket Cloud commit status creation

---

scm/driver/gitlab/repo.go

fix: Set description on GitLab commit statuses

---

scm/driver/gitlab/pr.go
scm/driver/gitlab/testdata/merge.json
scm/driver/gitlab/testdata/merge.json.golden

Part of https://github.com/jenkins-x/lighthouse/issues/693

fix: Use GitLab's work-in-progress as draft value

---

scm/driver/gitlab/pr.go
scm/driver/gitlab/testdata/merge.json.golden
scm/driver/gitlab/testdata/merges.json.golden
scm/driver/gitlab/testdata/pr_create.json.golden

fix: Include state on GitLab PRs

---

scm/driver/gitlab/integration/pr_test.go
scm/driver/gitlab/issue.go
scm/driver/gitlab/pr.go
scm/driver/gitlab/testdata/issue.json.golden
scm/driver/gitlab/testdata/issues.json.golden
scm/driver/gitlab/testdata/merge.json.golden
scm/driver/gitlab/testdata/merges.json.golden
scm/driver/gitlab/testdata/pr_create.json.golden
scm/driver/gitlab/testdata/webhooks/pull_request_close.json.golden
scm/driver/gitlab/testdata/webhooks/pull_request_comment_create.json.golden
scm/driver/gitlab/testdata/webhooks/pull_request_create.json.golden
scm/driver/gitlab/testdata/webhooks/pull_request_merge.json.golden
scm/driver/gitlab/testdata/webhooks/pull_request_reopen.json.golden
scm/driver/gitlab/util.go
scm/driver/gitlab/webhook.go

fix: PR state on GitLab webhooks, issue state as well.

---

scm/driver/gitlab/testdata/webhooks/pull_request_edited.json
scm/driver/gitlab/testdata/webhooks/pull_request_edited.json.golden
scm/driver/gitlab/webhook.go
scm/driver/gitlab/webhook_test.go

fix: Edited GitLab MR should be an update action, not a sync

---

scm/driver/bitbucket/repo.go
scm/driver/fake/repo.go
scm/driver/gitea/repo.go
scm/driver/github/repo.go
scm/driver/gitlab/repo.go
scm/driver/gitlab/repo_test.go
scm/driver/gogs/repo.go
scm/driver/stash/repo.go
scm/factory/examples/contributors/main.go
scm/repo.go

fix: Add ListOptions to ListCollaborators

---

scm/driver/fake/utils.go

fix: Return everything for page 0 _or_ size 0 in fake

---

scm/driver/gitlab/testdata/contributors.json.golden
scm/driver/gitlab/testdata/issue_events.golden.json
scm/driver/gitlab/testdata/pr_events.golden.json
scm/driver/gitlab/testdata/user.json.golden
scm/driver/gitlab/testdata/user_search.json.golden
scm/driver/gitlab/user.go

fix: Include ID in GitLab user transformation

---

scm/driver/gitlab/pr.go
scm/driver/gitlab/testdata/merge.json
scm/driver/gitlab/testdata/merge.json.golden
scm/driver/gitlab/testdata/merges.json.golden
scm/driver/gitlab/testdata/pr_create.json.golden

fix: Include assignees in GL MR info, and use IDs there.

---

scm/driver/stash/pr.go
scm/driver/stash/pr_test.go

I should have done this in the previous PR. oops.

fix: BBS edit comment needs version

---

scm/driver/github/pr.go
scm/driver/github/testdata/pr_create.json.golden
scm/driver/stash/pr.go
scm/driver/stash/testdata/pr.json
scm/driver/stash/testdata/pr.json.golden
scm/pr.go

chore: Add separate reviewers field to scm.PullRequest

---

OWNERS
jenkins-x.yml

chore: Add GOPROXY to release pipeline

---

scm/driver/stash/pr.go
scm/driver/stash/pr_test.go
scm/driver/stash/testdata/pr_comments.json
scm/driver/stash/testdata/pr_comments.json.golden

fix: Properly fetch/handle BitBucket Server PR comment listing

---

scm/driver/bitbucket/pr.go
scm/driver/fake/pr.go
scm/driver/gitea/pr.go
scm/driver/github/pr.go
scm/driver/github/pr_test.go
scm/driver/github/testdata/pr_update.json
scm/driver/gitlab/pr.go
scm/driver/gitlab/pr_test.go
scm/driver/gitlab/testdata/pr_update.json
scm/driver/gogs/pr.go
scm/driver/stash/pr.go
scm/driver/stash/pr_test.go
scm/driver/stash/testdata/pr_update.json
scm/pr.go

Initial implementations for BitBucket Server, GitHub, GitLab. Kinda
sparse, but it works.

feat: Add updating of pull requests

---

scm/driver/stash/testdata/webhooks/pr_modified.json
scm/driver/stash/testdata/webhooks/pr_modified.json.golden
scm/driver/stash/webhook.go
scm/driver/stash/webhook_test.go

fix: Add pr:modified hook for BitBucket Server

---

scm/driver/stash/pr.go
scm/driver/stash/testdata/pr.json.golden
scm/driver/stash/testdata/prs.json.golden
scm/driver/stash/testdata/webhooks/pr_comment.json.golden
scm/driver/stash/testdata/webhooks/pr_declined.json.golden
scm/driver/stash/testdata/webhooks/pr_merged.json.golden
scm/driver/stash/testdata/webhooks/pr_modified.json.golden
scm/driver/stash/testdata/webhooks/pr_open.json.golden
scm/driver/stash/testdata/webhooks/pr_ref_updated.json.golden
scm/driver/stash/webhook.go
scm/driver/stash/webhook_test.go

fix: Include ref in BBS PRs, fix latest commit for base as well

---

scm/driver/stash/org.go

fix: Implement IsAdmin for BitBucket Server

---

scm/driver/stash/org.go
scm/driver/stash/org_test.go
scm/driver/stash/testdata/org_members.json
scm/driver/stash/testdata/org_members.json.golden

fix: Add BBS ListOrgMembers and tests for IsAdmin/IsMember

---

scm/driver/stash/pr.go
scm/driver/stash/pr_test.go

fix: Pass PR version to BitBucket Server PR merge

---

scm/driver/stash/stash.go

fix: Disable XSRF check on BitBucket Server

---

scm/driver/gitlab/content.go
scm/driver/gitlab/content_test.go
scm/driver/gitlab/git.go
scm/driver/gitlab/git_test.go
scm/driver/gitlab/testdata/create_branch.json
scm/driver/gitlab/testdata/create_branch.json.golden

Two new methods for the "gitlab" driver, the ability to CreateRefs and Files.

feat: Implement CreateRef and CreateContent for GitLab.

---

scm/driver/bitbucket/review.go
scm/driver/fake/review.go
scm/driver/gitea/review.go
scm/driver/github/review.go
scm/driver/github/review_test.go
scm/driver/github/testdata/reviews_create.json
scm/driver/github/testdata/reviews_dismiss.json
scm/driver/github/testdata/reviews_find.json
scm/driver/github/testdata/reviews_find.json.golden
scm/driver/github/testdata/reviews_list.json
scm/driver/github/testdata/reviews_list.json.golden
scm/driver/github/testdata/reviews_list_comments.json
scm/driver/github/testdata/reviews_list_comments.json.golden
scm/driver/github/testdata/reviews_submit.json
scm/driver/github/testdata/reviews_update.json
scm/driver/github/testdata/webhooks/pr_review_submitted.json.golden
scm/driver/github/webhook.go
scm/driver/gitlab/review.go
scm/driver/gogs/review.go
scm/driver/stash/review.go
scm/example_test.go
scm/review.go

So let's make it handle actual reviews. GitHub implemented, will do something for Stash shortly.

fix: Reviews service was just comments

---

scm/driver/gitlab/content.go
scm/driver/gitlab/content_test.go
scm/driver/gitlab/testdata/content_update.json

This implements Update to allow updating of files in GitLab.

feat: Add updating of files to GitLab.

---

scm/driver/bitbucket/repo.go
scm/driver/bitbucket/repo_test.go
scm/driver/bitbucket/testdata/status.json.golden
scm/driver/bitbucket/testdata/statuses.json.golden
scm/driver/github/repo.go
scm/driver/github/testdata/combined_status.json.golden
scm/driver/github/testdata/status.json.golden
scm/driver/github/testdata/statuses.json.golden
scm/factory/examples/changes/main.go
scm/factory/examples/commits/main.go
scm/repo.go

so that you can query the Link for CI statuses on commits

fix: add support for Status.Link

---

scm/driver/gitlab/repo.go
scm/driver/gitlab/repo_test.go
scm/driver/gitlab/testdata/add_collaborator.json
scm/driver/gitlab/testdata/add_collaborator_user.json

feat: Add support for adding collaborators to repos in GitLab

---

scm/driver/gitlab/gitlab.go
scm/driver/gitlab/org.go
scm/driver/gitlab/repo.go
scm/driver/gitlab/repo_test.go
scm/driver/gitlab/testdata/create_project.json
scm/driver/gitlab/testdata/find_namespace.json
scm/driver/gitlab/testdata/group.json.golden
scm/driver/gitlab/testdata/groups.json.golden
scm/driver/stash/repo.go
scm/driver/stash/repo_test.go
scm/driver/stash/testdata/create_repo.json

fix: Implement repo creation for GitLab and BitBucket Server

---

scm/driver/bitbucket/repo.go
scm/driver/fake/repo.go
scm/driver/gitea/repo.go
scm/driver/github/repo.go
scm/driver/github/repo_test.go
scm/driver/github/testdata/repo_fork_input.json
scm/driver/gitlab/repo.go
scm/driver/gitlab/repo_test.go
scm/driver/gitlab/testdata/fork_project.json
scm/driver/gogs/repo.go
scm/driver/stash/repo.go
scm/driver/stash/repo_test.go
scm/driver/stash/testdata/fork_repo.json
scm/repo.go
updatebot.sh

Implementations initially for GitHub, GitLab, and BitBucket Server

feat: Add Fork to repository service

---

scm/driver/fake/content.go
scm/driver/fake/content_test.go
scm/driver/fake/data.go
scm/driver/fake/fake.go
scm/driver/fake/test_data/myorg/myrepo/README.md
scm/driver/fake/test_data/myorg/myrepo/somedir/something.txt

so we can use the fake driver to test the use of the Content API

fix: add support for content to fake

---

scm/driver/github/pr.go
scm/driver/gitlab/pr.go
scm/driver/gitlab/testdata/commit_diff.json.golden
scm/driver/gitlab/testdata/merge_diff.json.golden
scm/driver/stash/git.go
scm/driver/stash/testdata/changes.json.golden
scm/factory/factory.go
scm/pr.go

fix: Add PreviousPath to scm.Change

---

scm/driver/github/pr.go
scm/driver/github/testdata/changes.json.golden
scm/driver/github/testdata/pr_files.json.golden
scm/driver/gitlab/pr.go
scm/driver/gitlab/testdata/commit_diff.json.golden
scm/driver/gitlab/testdata/merge_diff.json.golden
scm/pr.go

chore: Add Patch field to scm.Change

---

scm/driver/stash/org.go
scm/driver/stash/pr.go
scm/driver/stash/pr_test.go
scm/driver/stash/repo.go
scm/driver/stash/repo_test.go
scm/driver/stash/testdata/add_collaborator.json
scm/driver/stash/testdata/find_user_permission.json

We'll need these for testing BitBucket Server with Lighthouse without Jenkins X involved.

feat: Add repo AddCollaborator and Create PR for BitBucket Server 

---

scm/driver/stash/content.go
scm/driver/stash/git.go
scm/driver/stash/pr.go
scm/driver/stash/repo.go
scm/driver/stash/user.go

fixes https://github.com/jenkins-x/lighthouse/issues/1017

fix: Query/path escape user and ref in BitBucket Server

---

scm/driver/gitea/git.go

fix: Trim `heads/` from gitea DeleteRef

---

scm/driver/bitbucket/repo.go
scm/driver/fake/repo.go
scm/driver/gitea/repo.go
scm/driver/github/repo.go
scm/driver/gitlab/repo.go
scm/driver/gogs/repo.go
scm/driver/stash/repo.go
scm/repo.go

This PR adds delete repo support (for Gitea only atm).
/cc @abayer

feat: add delete repo support

---

scm/driver/bitbucket/org.go
scm/driver/fake/org.go
scm/driver/gitea/org.go
scm/driver/github/org.go
scm/driver/gitlab/org.go
scm/driver/gogs/org.go
scm/driver/stash/org.go
scm/org.go

This PR adds support for Creating/Deleting organizations.

feat: add Create/Delete organization

---

scm/driver/bitbucket/user.go
scm/driver/fake/user.go
scm/driver/gitea/user.go
scm/driver/github/user.go
scm/driver/gitlab/user.go
scm/driver/gogs/user.go
scm/driver/stash/user.go
scm/user.go

This PR adds CreateToken/DeleteToken for users.

feat: add CreateToken/DeleteToken for users

---

scm/driver/gitlab/testdata/webhooks/pull_request_edited.json
scm/driver/gitlab/testdata/webhooks/pull_request_edited.json.golden
scm/driver/gitlab/webhook.go

fix: gitlab use oldrev field on merge request hook in pullRequestHook.changes

---

scm/driver/gitlab/gitlab.go
scm/driver/gitlab/testdata/find_namespace.json

Possible follow-up/replacement for #192

fix: Handle GitLab namespace query as an array properly

---

scm/driver/gitlab/content.go

Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>

fix: gitlab add ability to list files

---

scm/driver/gitlab/content_test.go
scm/driver/gitlab/testdata/content_list.json
scm/driver/gitlab/testdata/content_list.json.golden

fix: add unit test for listing contents with gitlab

---

scm/driver/github/repo.go

fix: add support for delete repository on github

---

scm/driver/fake/pr.go

Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>

fix: implement pr.assignIssue in fake driver

---

scm/driver/fake/release.go
scm/driver/github/release.go
scm/driver/github/testdata/release.json.golden
scm/driver/github/testdata/releases.json.golden

used the wrong property name, whoops

fix: use correct description json encoding for releases

---

scm/driver/gitlab/repo.go
scm/driver/gitlab/testdata/merge.json.golden
scm/driver/gitlab/testdata/merges.json.golden
scm/driver/gitlab/testdata/pr_create.json.golden
scm/driver/gitlab/testdata/repo.json.golden
scm/driver/gitlab/testdata/repos.json.golden

Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>
this needed by jx-preview to correctly garbage collect

fix: set correct value for Repository.Link when using gitlab

---

.gitignore
scm/driver/gitea/testdata/webhooks/push.json.golden
scm/driver/gitea/webhook.go

Fixes https://github.com/jenkins-x/lighthouse/issues/1180
As well as adding in two other fields that match the pull event structure

Gitea push hook additional fields

---

scm/driver/fake/pr.go

for easier testing of created PRs with fakes

fix: implement PullRequests.List for fake

---

scm/driver/stash/org.go
scm/driver/stash/org_test.go
scm/driver/stash/stash_test.go
scm/driver/stash/testdata/orgs.json
scm/driver/stash/testdata/orgs.json.golden

Added support for listing organisations from bitbucket server.
I have included a unit test evidencing the mapping working correctly based off a valid bitbucket response example

feat: added support for bitbucket server organisation listing

---

scm/driver/fake/pr.go

so we can more easily test labels on generated fake PRs

fix: better fake handling of labels on PRs

---

scm/deploy.go
scm/driver/github/deploy.go
scm/driver/github/integration/issue_test.go
scm/driver/github/integration/org_test.go
scm/driver/github/integration/pr_test.go
scm/driver/github/integration/user_test.go
scm/driver/github/testdata/deploy.json.golden
scm/driver/github/testdata/deploy_create.json.golden
scm/driver/github/testdata/deploys.json.golden
scm/driver/github/testdata/webhooks/deployment.json.golden
scm/driver/github/testdata/webhooks/deployment_status.json.golden
scm/driver/github/webhook.go
scm/webhook.go

deployment & deployment_status webhooks were half-implemented.
with this change, both are now fully implemented.

fix: deployment/deployment_status webhooks implementation

---

scm/driver/fake/data.go
scm/driver/fake/deploy.go
scm/driver/fake/deploy_test.go
scm/driver/fake/fake.go
scm/driver/github/deploy.go
scm/driver/github/deploy_test.go

so we can fake out testing deployments

fix: add a fake deployments implementation

---

scm/client.go
scm/driver/bitbucket/repo.go
scm/driver/fake/deploy.go
scm/driver/fake/deploy_test.go
scm/driver/github/deploy.go
scm/driver/gitlab/webhook.go
scm/factory/factory.go

fix: add support for creating repositories

---

scm/driver/bitbucket/repo.go
scm/driver/bitbucket/repo_test.go

as they were failing due to a bad webhook event
also add better error reporting

fix: improve bitbucket cloud webhooks

---

scm/driver/bitbucket/git.go
scm/driver/bitbucket/issue.go
scm/driver/bitbucket/pr.go
scm/driver/bitbucket/testdata/webhooks/pr_created.json.golden
scm/driver/bitbucket/testdata/webhooks/pr_declined.json.golden
scm/driver/bitbucket/testdata/webhooks/pr_fulfilled.json.golden
scm/driver/bitbucket/testdata/webhooks/pr_updated.json.golden
scm/driver/bitbucket/testdata/webhooks/push.json.golden
scm/driver/bitbucket/testdata/webhooks/push_branch_create.json.golden
scm/driver/bitbucket/testdata/webhooks/push_tag_create.json.golden
scm/driver/bitbucket/webhook.go

so that we get the full SHAs for PullRequest and PushHook
and populate the Base + Head of PullRequests better
this lets us use bitbucket cloud better inside lighthouse

fix: improve the webhook parsing for bitbucket cloud

---

scm/driver/bitbucket/repo.go

https://kubernetes.slack.com/archives/C9LTHT2BB/p1616165067094400?thread_ts=1616077422.055700&cid=C9LTHT2BB

Set the is_private flag to true

---

scm/driver/bitbucket/issue.go
scm/driver/bitbucket/pr.go
scm/driver/stash/issue.go
scm/driver/stash/pr.go
scm/labels/labels.go

so we can reuse the comment label logic for bitbucket cloud too

fix: refactor the label comment code

---

scm/driver/github/repo.go
scm/driver/github/repo_test.go
scm/repo.go

feat: create hooks with deployment events

---

scm/driver/bitbucket/repo.go

Add implementation of functions ListCollaborators and IsCollaborator in repo.go for bitbucket driver.
Tested by building jx-project. No unit/integration tests are added.

fix: Enhance bitbucket driver support

---

scm/driver/fake/fake.go
scm/driver/fake/repo.go
scm/driver/fake/repo_test.go
scm/driver/fake/test_helpers.go
scm/factory/examples/repo/main.go
scm/util.go

so that Create() and Fork() return the clone URL and add some more tests

fix: improve fake driver

---

scm/driver/gitlab/testdata/webhooks/issue_comment_create.json.golden
scm/driver/gitlab/webhook.go
scm/driver/gitlab/webhook_test.go

feat: add gitlab issue hook support

---

scm/driver/gitlab/webhook.go

fix: Update webhook.go

---

scm/driver/bitbucket/testdata/webhooks/push.json.golden
scm/driver/bitbucket/testdata/webhooks/push_branch_create.json.golden
scm/driver/bitbucket/testdata/webhooks/push_tag_create.json.golden
scm/driver/bitbucket/webhook.go
scm/driver/bitbucket/webhook_test.go

same as #267 but implemented for bitbucketcloud too now

fix: add webhook GUID for bitbucketcloud

---

scm/factory/factory.go

This change allows the client to be associated to a Workspace, as opposed
to an individual user
A user can create a OAuth Consumer in their workspace, add the necessary scopes, and set it as a private consumer.
They can then provide the clientID and clientSecret in the `GIT_TOKEN` variable.
```
~/c/p/go-scm feat/bb-oauth• 1.4s [1] GIT_KIND=bitbucketcloud GIT_TOKEN=abc:xyz go run scm/factory/examples/repos/main.go
using driver: bitbucketcloud and serverURL:
listing repositories
Found 620 repositories
```
Basic Auth will still work if you provide a username, (using Bitbuckets App Passwords)
```
~/c/p/go-scm feat/bb-oauth• 10.6s ❱ GIT_KIND=bitbucketcloud GIT_USERNAME=my-username GIT_TOKEN=xyz go run scm/factory/examples/repos/main.go
using driver: bitbucketcloud and serverURL:
listing …
```

feat: add 2-leg oauth flow for bitbucket cloud

---

scm/driver/gitlab/testdata/webhooks/pull_request_merge.json.golden
scm/driver/gitlab/webhook.go

fix config-updater not work with gitlab

fix: config-updater not work with gitlab

---

scm/driver/gitlab/org.go
scm/driver/gitlab/repo.go
scm/driver/gitlab/repo_test.go

so that all groups are queried with inheritance

fix: add back /all for gitlab

---

scm/driver/bitbucket/pr.go

Keeper attempted merging of PRs with merge conflict which led to "bad request" during each sync cycle.
The PRs with merge conflict could not be filtered out since BBC PR object did not have merge state info populated.
Change is added to populate merge state attributes in the PR object.

fix: Initialize merge state attributes of PR for BBC

---

scm/driver/bitbucket/repo.go

* fix: initialize CombinedStatus with computed combined state value

fix: initialize CombinedStatus with computed combined state value (BBC)

---

scm/driver/gitlab/pr.go
scm/factory/examples/addlabel/main.go

this approach works much more reliably

fix: adding/removing labels on gitlab

---

scm/driver/stash/org.go
scm/driver/stash/org_test.go
scm/driver/stash/repo.go
scm/driver/stash/testdata/group_members.json
scm/driver/stash/testdata/project_groups.json

fix: trigger jobs for users part of groups assigned to project

---

go.mod

refactor: upgrade to go 1.17.9

---

.lighthouse/jenkins-x/lint.yaml
.lighthouse/jenkins-x/pullrequest.yaml
.lighthouse/jenkins-x/release.yaml

fix: remove resource request from step template

---

scm/driver/fake/pr.go

Allows for additional testing of [jx-scm](https://github.com/jenkins-x-plugins/jx-scm).

fix: implement fake scm driver's pull request update command

---

scm/driver/bitbucket/repo.go
scm/driver/bitbucket/repo_test.go
scm/driver/bitbucket/testdata/repos-single.json.golden

See the official document https://developer.atlassian.com/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-get

Add repositories list in an organization for bitbucket

---

go.mod
go.sum
scm/factory/examples/pr/main.go
scm/factory/examples/prlabel/main.go

This also fixes the dependabot security alert with yaml.v2.

fix: remove unmaintained ghodss package

---

go.mod
go.sum

Locally I was unable to build this without updating the sys pacakge.

fix: unable to build locally

---

go.mod
go.sum

chore(deps): bump transient dependency protobuf

---

.golangci.yml
go.mod
hack/linter.sh

related to [jenkins-x/jx#8433](https://github.com/jenkins-x/jx/issues/8433)

chore: Upgrade go version to 1.19 and golangci lint to 1.50.1

---

scm/driver/gitlab/repo.go
scm/driver/gitlab/repo_test.go
scm/driver/gitlab/testdata/hook_ssl_false.json
scm/driver/gitlab/testdata/hook_ssl_false.json.golden

fix: the gitlab hook ssl verify setting incorrect

---

scm/driver/gitlab/repo.go
scm/driver/gitlab/repo_test.go

This issue was caused by https://github.com/jenkins-x/go-scm/pull/363

fix: the logic of if skip tls is incorrect

---

scm/driver/gitea/testdata/issue.json.golden
scm/driver/gitea/user.go

fixes jenkins-x/lighthouse#1433

fix: use gitea admin

---

scm/driver/stash/content.go
scm/driver/stash/content_test.go
scm/driver/stash/testdata/content_update.json

Content update updates a file in repository refering it's commit SHA.

Implemented Content Update Endpoint for Bitbucket Server (stash)

---

scm/driver/stash/pr.go

Like its done in [ListChanges](https://github.com/jenkins-x/go-scm/blob/76ca270ce78520fc40c9386c8a675e8b4e4ace2b/scm/driver/stash/git.go#L130) of a commit.

Add Pagination in Pull Request Changes List Changes on Bitbucket Server (stash)

---

hack/linter.sh
scm/client.go
scm/driver/bitbucket/bitbucket.go
scm/driver/github/repo_test.go
scm/driver/stash/stash.go

We also removed errors that are not used anymore

fix: capitalization of error to match standard Http errors
