scm/driver/gitlab/testdata/webhooks/pull_request_close.json.golden
scm/driver/gitlab/testdata/webhooks/pull_request_create.json.golden
scm/driver/gitlab/testdata/webhooks/pull_request_merge.json.golden
scm/driver/gitlab/testdata/webhooks/pull_request_reopen.json.golden
scm/driver/gitlab/webhook.go
scm/driver/stash/pr.go
scm/driver/stash/testdata/pr.json.golden
scm/driver/stash/testdata/prs.json.golden
scm/driver/stash/testdata/webhooks/pr_comment.json.golden
scm/driver/stash/testdata/webhooks/pr_declined.json.golden
scm/driver/stash/testdata/webhooks/pr_merged.json.golden
scm/driver/stash/testdata/webhooks/pr_open.json.golden
scm/driver/stash/webhook.go

we were populating PullRequestHook.Base.Ref with the sha and not populating the ref/branch for stash + gitlab

fix: fix use of branch/ref and sha in PullRequestHook

---

scm/driver/github/pr.go
scm/driver/github/testdata/pr.json
scm/driver/github/testdata/pr.json.golden
scm/driver/github/testdata/webhooks/pr_labeled.json.golden
scm/pr.go

Adds labels to PullRequest for the GitHub driver for #21 
Does not include an integration test, since no PR in the example repo or the drone/go-scm repo have a sample labelled PR (AFAICT anyway).

fix: Add GitHub PullRequest Labels

---

scm/client.go
scm/driver/github/github.go
scm/driver/github/github_test.go

Exposes Client.GraphQLURL to enable testing.
fixes #31

fix: github enterprise graphql endpoint url

---

scm/const.go
scm/driver/bitbucket/testdata/status.json.golden
scm/driver/bitbucket/testdata/statuses.json.golden
scm/driver/gitea/testdata/status.json.golden
scm/driver/gitea/testdata/statuses.json.golden
scm/driver/github/testdata/combined_status.json.golden
scm/driver/github/testdata/status.json.golden
scm/driver/github/testdata/statuses.json.golden
scm/driver/gitlab/testdata/status.json.golden
scm/driver/gitlab/testdata/statuses.json.golden
scm/driver/stash/testdata/commit_build_status.json.golden

This converts JSON serialization of statuses into their string
representation. e.g.
Old:
```
{
"state": 3,
}
```
New:
```
{
"state": "success",
}
```

fix; Add JSON marshalling support for State codes.

---

scm/const.go
scm/const_test.go

Fixes breakage when using json.Marshal introduced in
fad5b44456ec8ba9c04161449d8ca37ab1a37ae9.
Not entirely sure why the other tests in the previous commit succeeded, so also
makes sure this is tested explicitly.

fix: json.Marshal for State.

---

scm/driver/fake/pr.go

This updates the fake driver's PullRequests.Create method to record the newly created PullRequest,
so that it can be fetched with the ID from the PullRequest that was created.

feat: Record the create pull request in the fake driver.

---

scm/driver/gitlab/gitlab.go
scm/driver/gitlab/gitlab_test.go

The GitLab client was broken for POST requests, ignoring the request body argument.
This fixes this issue, and adds tests for request and response bodies.

fix: Add tests and fix for the GitLab client.

---

scm/driver/github/repo.go
scm/driver/github/testdata/statuses.json

GitHub keeps multiple versions of a check with the same label.
The API returns the list in reverse chronological order:
https://developer.github.com/v3/repos/statuses/#list-statuses-for-a-specific-ref.
The status resource in go-scm does not expose any information
that might help distinguish between versions of checks with
the same label.
When a client of go-scm receives a list of statuses that contain
duplicate labels, it has no way of finding out which one is the
most recent one.
Change the github driver to filter the statuses and only return
one (the most recent) for each label.
Fixes #79

fix: filter statuses in the github driver

---

scm/driver/github/org.go
scm/org.go

I'm not sure how to test this as it only works on orgs that the user belongs to.
I've manually fudged the test to make it work (but reverted before i made this PR)

feat: include member repo creation perms in org

---

scm/driver/fake/pr.go
scm/driver/fake/pr_test.go
scm/driver/fake/utils.go

This implements pagination of the ListChanges (using the ListOption settings) of the fake driver's `ListChanges` for PullRequests.
This calculates the start/end of the slice to return based on the data, and returns.
This pagination function is reusable in other fake methods.

feat: Paginate Fake driver PullRequest ListChanges

---

scm/driver/fake/pr_test.go
scm/driver/fake/utils.go

This updates the pagination to return all items if there's no size or page.

fix: If we have no default page or other options, respond with all items.

---

scm/driver/github/org.go
scm/driver/github/testdata/org.json
scm/driver/github/testdata/org.json.golden

Follow-up on PR https://github.com/jenkins-x/go-scm/pull/82 this PR make sure members can create private repos for a given org.
This is needed for https://github.com/cloudbees/jxui-frontend/issues/1295

fix: github org's permissions

---

scm/factory/factory.go
scm/factory/factory_test.go

This adds support for client option functions to be passed when creating a new
scm.Client using the factory function.
A single option func is provided 'factory.Client' which allows injection of a
custom HTTP client at construction time.

feat: Add support for factory options.

---

scm/driver/github/github.go

Support consistent error handling across providers (at least regarding `github` and `fake` driver for now) when it comes to resources that could not be found.
fake driver already behaves correspondingly. However since it does not
return a HTTP response it is not possible to have one condition for
a 'not found' error that works for both providers. This PR makes that
possible now.

Make github driver return scm.ErrNotFound.

---

scm/driver/fake/org.go
scm/driver/gitlab/pr.go
scm/driver/gitlab/webhook.go
scm/driver/gitlab/webhook_test.go
scm/driver/stash/testdata/webhooks/pr_ref_updated.json
scm/driver/stash/testdata/webhooks/pr_ref_updated.json.golden
scm/driver/stash/webhook.go
scm/driver/stash/webhook_test.go

Introduced in BitBucket Server 7.0 - as far as I can tell, there isn't yet an equivalent in BitBucket Cloud.
fixes https://github.com/jenkins-x/lighthouse/issues/511

fix: Handle BitBucket Server "pr:from_ref_updated" hook

---

scm/driver/fake/data.go
scm/driver/fake/org.go

Currently the fake driver does not support finding an organization.
Since I require this for a test I added the capability to configure a predefined set of organizations (as it was done for repositories already).
The organization listing endpoint always returned hardcoded values. To make it consistent while not breaking the current behaviour this PR makes it return the preconfigured organizations IF the slice is specified/not nil.

feat: Configurable fake organizations.

---

scm/driver/github/org.go

Now that github supports unlimited private repos on free teams. the check if an org is not free tier can be dropped.
Further more, it not only can be dropped but needs to be dropped because the github api still reports 0 private repos available even though it lets a user create them
Exert of response from  https://api.github.com/orgs/dire-kiwi
```
"total_private_repos": 1,
"owned_private_repos": 1,
"members_can_create_public_repositories": true,
"members_can_create_private_repositories": true,
"members_can_create_internal_repositories": false,
"plan": {
"name": "free",
"space": 976562499,
"private_repos": 0,
"filled_seats": 2,
"seats": 0
}
```

feat: update permissions data

---

scm/driver/gitlab/repo.go
scm/driver/gitlab/repo_test.go

Otherwise we need an extra API call to look up the user's ID from the login.

fix: Get full user list for permissions check on GitLab

---

scm/driver/gitlab/pr.go
scm/driver/gitlab/testdata/merge.json.golden
scm/driver/gitlab/testdata/merges.json.golden
scm/driver/gitlab/testdata/pr_create.json.golden

fix: Shouldn't include "refs/heads/" in GitLab MR base/target refs

---

scm/driver/gitlab/pr.go

fix: Need to specify 0 as assignee id when removing all existing ones from GitLab

---

scm/driver/fake/data.go
scm/driver/fake/repo.go
scm/driver/fake/repo_test.go

This PR proposes the following changes to Fake Client.
* Use hook ID to find target hook to delete instead of using hook name.  
* CreateHook to generate a hook ID instead of using "dummy".   
* Initialize fake `Data`'s `Hooks map` 
The above changes allow more meaningful mocking/testing.   Note:.  if tests want to use `factory.NewClient("fake", "", "")`to construct a client, fake `Data` is not available to test code.

fix: Fake client to create hook with generated ID and delete hook by ID.

---

scm/driver/stash/pr.go
scm/driver/stash/pr_test.go
scm/driver/stash/repo.go
scm/driver/stash/repo_test.go
scm/driver/stash/testdata/combined_status.json.golden
scm/driver/stash/testdata/commit_build_status.json
scm/driver/stash/testdata/commit_build_status.json.golden
scm/driver/stash/testdata/find_user_permission.json

Specifically `RequestReview`, `UnrequestReview`, PR `EditComment`, PR `DeleteComment`, PR `AssignIssue` (falling back on `RequestReview`), PR `UnassignIssue` (falling back on `UnrequestReview`), `FindUserPermission`, `FindCombinedStatus`.

chore: Add a number of BitBucket Server implementations

---

scm/driver/stash/pr.go
scm/driver/stash/pr_test.go
scm/driver/stash/testdata/pr_comment.json
scm/driver/stash/testdata/pr_comment.json.golden
scm/issue.go

Since we need this for deleting or editing BitBucket Server comments.

fix: Add Version to scm.Comment

---

scm/content.go
scm/driver/github/content.go
scm/driver/github/content_test.go
scm/driver/github/testdata/content.json.golden

This implements creation and updating of files in a GitHub repository.
`scm.Content` has the `Sha` added, because it's needed to do an update, and this saves an extra call to `List` to get it.
This makes it easy to do something like:
```go
content, _, err := client.Contents.Find(
context.Background(),  "example/repo", "README", "master")
params := &scm.ContentParams{
Branch:  "master",
Message: "Automated update",
Data:    []byte("# Just a test\n"),
Sha:     content.Sha,
}
response, err := client.Contents.Update(
context.Background(), "example/repo", "README", params)
```

feat: Implement GitHub create/update of a repository file.

---

scm/driver/bitbucket/git.go
scm/driver/fake/git.go
scm/driver/gitea/git.go
scm/driver/github/git.go
scm/driver/github/git_test.go
scm/driver/github/testdata/ref.json
scm/driver/github/testdata/ref.json.golden
scm/driver/gitlab/git.go
scm/driver/gogs/git.go
scm/driver/stash/git.go
scm/git.go

This provides functionality for creating new refs, e.g. 
```go
_, response, err := client.Git.CreateRef(
context.Background(), "demo/repo", "refs/heads/testing", 
"82291b8e61fa5df765ddb4b3f5cb5f09bdcf4b62")
```

feat: Add support for creating new refs in GitHub.

---

scm/driver/gitlab/webhook.go

This changes the GitLab Webhook parsing implementation from a simple (insecure)
string comparison to a more secure constant-time comparison between the token
and the secret.

feat: Use constant-time comparison for the GitLab token.

---

scm/driver/github/repo.go

fixes https://github.com/jenkins-x/go-scm/issues/147
Current behaviour:
repositoryService.List returns the list of all public repos user has access to accross all organizations.
Desired behaviour:
This List method now returns the list of all repos on which the user is a owner.
In case we have a token in the header of the request, it will return both public and private. If we don't have a token it will return public only.
Open question:
I'm not sure this is the best place to achieve that or if I should update the ListUser method here: https://github.com/jenkins-x/go-scm/compare/master...romainverduci:list-user-private-repos?expand=1#diff-2a18725c234b64fe3425404bfbe3abd3R213
The requirement is that I need a way to get the list of public and private repos for a given user authenticated by …

fix: list user private repos

---

scm/driver/github/integration/git_test.go
scm/driver/github/util.go
scm/example_test.go
scm/git.go

Hey,
According to the docs (see reference), the `sha` parameter should be
used to list commits of a specific branch.
Reference:
- https://developer.github.com/v3/repos/commits/#list-commits
Thanks!

fix: github: add sha parameter for listing commits

---

scm/factory/drivers.go
scm/factory/drivers_test.go
scm/factory/factory.go
scm/factory/factory_test.go

In addition, the function `factory.FromRepoURL(s string)` accepts a string of the
form "https://:password@hostname/" can be used to create a client from
the URL, determining the auth token, endpoint and driver automatically
(if possible).
This adds functionality for identifying the driver for an scm.Client
from a hostname, including customising this from the environment
variable `GIT_DRIVERS`.
Putting a list of the form "gl.example.com=gitlab,gh.example.com=github"
into the `GIT_DRIVERS` environment variable provides a way to add
additional hostname to driver mappings.
```go
// works for public repos on GitHub.com
client, err := factory.FromRepoURL("https://github.com")
```
```go
// export GIT_REPO_URL=https://:<insert token>@github.com/ works
client, err := …
```

feat: Automatically identify the driver from a URL.

---

go.mod
scm/driver/gitlab/gitlab.go

-  Adds a generic GraphQL client on gitlab driver (github.com/shurcooL/graphql)

feat: Adding GraphQL for gitlab

---

scm/driver/github/repo.go

we need to use relative links rather than absolute as on GitHub Enterprise the client URL includes things like `/api/v3/` prefix which we need to preserve
Signed-off-by: jstrachan <jenkins-x@googlegroups.com>

fix: for GitHub Enterprise

---

scm/driver/fake/content.go
scm/driver/fake/content_test.go
scm/driver/fake/test_data/test_refs/myorg/myrepo/README.md
scm/driver/fake/test_data/test_refs/myorg/myrepo/refs/master/something.txt
scm/driver/fake/test_data/test_refs/myorg/myrepo/refs/mybranch/something.txt

so you can more easily create the fake git provider with different content in different refs using the convention of `test_data/$owner/$repo/refs/$ref/$fileName`

fix: make testing content with refs easier for fake

---

scm/driver/gitea/git.go

This PR adds DeleteRef support to gitea.
Not sure how to deal with `refs/` `heads/` etc...
For example, in Lighthouse, the branchcleaner plugin formats the branch name `heads/name` (see [here](https://github.com/jenkins-x/lighthouse/blob/5fd1d1f5e64ec136ed18591181f1e863e0667cca/pkg/plugins/branchcleaner/branchcleaner.go#L63)).
/cc @abayer

chore: add DeleteRef to gitea

---

scm/driver/gitea/git.go

This PR returns an error when deleting a branch returns false in the Gitea provider.
/cc @abayer

chore: return an error when deleting a branch returns false (gitea)

---

scm/driver/gitlab/gitlab_test.go
scm/driver/gitlab/org.go
scm/driver/gitlab/repo.go
scm/driver/gitlab/repo_test.go
scm/driver/gitlab/user.go

A few GitLab functions need to list team members, statuses, and the like before finding the right return value, where GitHub/Gitea just requires a direct call. We need to automatically paginate for those functions to make sure we traverse all possibilities.
fixes #174

fix: Paginate for lookup-by-listing GitLab functions

---

scm/driver/gitea/gitea.go
scm/factory/factory.go

This PR adds basic auth factory (only for Gitea right now).
This is mandatory for some operations like creating tokens.

feat: add factory with basic auth

---

scm/driver/gitlab/pr.go
scm/driver/gitlab/util.go
scm/pr.go

When doing a Merge API Request there are a few options that Gitlab provides
which can be very useful. Another change in this PR allows to squash during the merge.
This behavior was not consistent with the current scm.PullRequestMergeOptions
and here it is adjusted to work as expected

feat: Add squash options to PullRequest merge for Gitlab

---

scm/driver/gitlab/gitlab.go

Jenkins X v3 is using go-scm to support different git providers. The error `error: failed to create git repository username/projectname: json: cannot unmarshal array into Go value of type gitlab.gl_namespace` occurred for the reason that it's trying to decode array into json. This pull request is to solve this issue by adding a specific function to ensure it's unmarshall json to `out`. 
Also, the previous `decode` in do() did not work well and always returned null/empty struct to `out`, and this pull request fix this issue.

fix: `json: cannot unmarshall array into Go value of type gitlab.gl_name`

---

scm/driver/gitlab/pr.go
scm/driver/gitlab/repo.go
scm/driver/gitlab/testdata/merge.json.golden
scm/driver/gitlab/testdata/merges.json.golden
scm/driver/gitlab/testdata/pr_create.json.golden

We depend on the `Name`, `Namespace`, and/or `FullName` fields being set in the `Base.Repo` for a PR in Lighthouse tests, so let's set them. We might want to change this up to query for the head/base repos in full, but this approach, while minimal, doesn't require additional API calls.

fix: Populate base repo in GitLab PRs

---

scm/driver/fake/content_test.go
scm/driver/fake/data.go
scm/driver/fake/repo.go
scm/driver/fake/user.go
scm/driver/fake/user_test.go

lets add a unit test to list invitations, add a collaborator and accept an invite and assert that the fake provider should behave as we'd expect

fix: improve fake support for invitations

---

go.mod
go.sum
scm/driver/gitlab/content.go
scm/driver/gitlab/pr.go
scm/driver/gitlab/pr_test.go
scm/driver/gitlab/testdata/merge.json.golden
scm/driver/gitlab/testdata/merges.json.golden
scm/driver/gitlab/testdata/other_repo.json
scm/driver/gitlab/testdata/pr_create.json
scm/driver/gitlab/testdata/pr_create.json.golden
scm/driver/gitlab/testdata/repo.json.golden
scm/driver/gitlab/testdata/repos.json
scm/driver/gitlab/testdata/repos.json.golden

GitLab just provides project IDs for source/target for merge requests, so we need to look up the repo information at some point. I've decided to move that logic into here rather than working around it in Lighthouse.
This could be optimized to do better caching - it already avoids looking up twice if the source and target repos are the same project ID, but we could do even more by adding a cache to the pull service. I feel like that's probably more work than strictly necessary so will defer for now.
Permanent fix for the issue seen on https://github.com/jenkins-x/lighthouse/pull/1108 (caused by #194, my attempt to deal with some of this issue) and worked around in https://github.com/jenkins-x/lighthouse/pull/1107/commits/35c0e09bced8ba0717ffe050ab142f174adc01c6
Signed-off-by: Andrew Bayer …

fix: Fetch repo info when converting GitLab PRs

---

scm/driver/bitbucket/repo.go

to avoid failing fast on lighthouse
fixes #86

fix: avoid failing on bitbucket cloud if we have no collaborators / labels

---

scm/driver/bitbucket/bitbucket.go
scm/driver/bitbucket/repo_test.go
scm/driver/github/github.go
scm/driver/gitlab/gitlab.go
scm/driver/gitlab/repo_test.go
scm/driver/gitlab/user_test.go

Current implementation fails to pass error messages back to users in the
case of some errors, notably 403 errors from gitlab. This commit borrows
the http error handling from the gitea driver and applies the
pattern to all of the other drivers.
Steps to reproduce:
Given an enterprise gitlab account, create:
- an access token that has only `read_user` permissions
- a private repo
Create a client using the above token.
Call the client's ListBranches method.
Expected:
an error that includes an indication that the client request was unauthorized/the http response status was 403.
Actual:
err.Error() = ""

Pass status code on http error

---

scm/driver/gitlab/pr.go
scm/driver/gitlab/pr_test.go
scm/driver/gitlab/testdata/merge.json.golden
scm/driver/gitlab/testdata/merges.json.golden
scm/driver/gitlab/testdata/pr_create.json.golden

The gitlab driver populates the scm.PullRequest field `Fork`, but the Gitlab driver does not. This pr ensures that gitlab prs populate this field.
Note: In `scm/driver/gitlab/pr_test.go` I have duplicated instantiating a number of gock doubles, as there is a new http call in the `pr.go` implementation. This gock duplication feels clunky and if there is a better pattern for enabling this, I would be happy to follow it.

fix: Gitlab pullrequests populates fork field

---

scm/driver/github/integration/git_test.go
scm/driver/gitlab/git.go
scm/driver/gitlab/integration/git_test.go

This was untestedin github. Test added.
This was untested and not implemented in gitlab. Implementation and test.

fix: Gitlab commits include url in `link` field

---

scm/client.go
scm/driver/bitbucket/git.go
scm/driver/bitbucket/git_test.go
scm/driver/fake/git.go
scm/driver/gitea/git.go
scm/driver/gitea/git_test.go
scm/driver/github/git.go
scm/driver/github/git_test.go
scm/driver/github/integration/git_test.go
scm/driver/github/integration/github_test.go
scm/driver/gitlab/git.go
scm/driver/gitlab/git_test.go
scm/driver/gitlab/integration/git_test.go
scm/driver/gitlab/integration/gitlab_test.go
scm/driver/gitlab/testdata/compare.json
scm/driver/gitlab/testdata/compare.json.golden
scm/driver/gitlab/util.go
scm/driver/gogs/git.go
scm/driver/gogs/git_test.go
scm/driver/stash/git.go
scm/driver/stash/git_test.go
scm/driver/stash/util.go
scm/git.go

ListChanges only shows the changes between a commit and its parent.
Viewing changes between a commit and another commit is useful.
The feature is supported by a number of the cloud repository providers
(github, gitlab, bitbucket).

CompareCommits for diff between 2 commits

---

scm/driver/gitea/release.go
scm/factory/examples/release/get.go

Gitea gives a http 500 error when a tag exists but a release hasn't been created yet, so workaound this until a fix is pushed upstream

Gitea release user doesnt exist workaround

---

scm/driver/gitea/release.go

this is also needed for the workaround to work.

fix: need to also return a 404 not found go error in the workaround

---

go.mod
scm/driver/gitlab/gitlab.go
scm/driver/gitlab/user.go
scm/driver/gitlab/webhook.go
scm/driver/gitlab/webhook_test.go

Currently, when the `convertMergeRequestCommentHook` method runs, it builds up a user object based on a single ID and uses that both in the PR object and the comment object. This results in Lighthouse not properly handling any `/lgtm` in comments, as the author is the same as the user leaving the comment. ref https://github.com/jenkins-x/lighthouse/issues/1154
This PR adds a simple method to the user service to fetch by ID (which is present in the incoming webhook payload), and an interface for use within the `webhookService`. 
Fixes: #211
Signed-off-by: Jeremy Rickard <rickardj@vmware.com>

fix: Update Gitlab Webhook Service to Fetch Users By ID

---

scm/driver/github/deploy.go

Closes #240
Please see the attached issue for more info, did not applied the `omitempty` on the boolean since the `false` is taken as empty value in golang and in that would be very difficult to set those params to `false` value on the deployment
Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Fix Creation of Git Deployment from the module

---

scm/driver/gitlab/testdata/webhooks/branch_create.json.golden
scm/driver/gitlab/testdata/webhooks/push.json.golden
scm/driver/gitlab/testdata/webhooks/tag_create.json.golden
scm/driver/gitlab/webhook.go

When convert a push webhook from gitlab, we forgot add the After field. We use this field in the creation of the lighthouse jobs (we use after as head).

fix: gitlab pushHook, add after field from webhook

---

scm/client.go
scm/driver/bitbucket/issue.go
scm/driver/bitbucket/issue_test.go
scm/driver/bitbucket/pr.go
scm/driver/bitbucket/repo.go
scm/driver/bitbucket/util.go
scm/factory/examples/combinedstatus/main.go

based on PR: https://github.com/jenkins-x/go-scm/pull/258 
fixed up the unit tests and added a first spike at combined status for bitbucket cloud

fix: added bitbucket cloud comment support

---

scm/driver/bitbucket/pr.go

Merge requests currently fail with Bad Request without the required payload.

fix: Adding required payload to merge requests

---

scm/driver/fake/release.go
scm/driver/gitea/release.go
scm/driver/gitea/testdata/webhooks/release.json
scm/driver/gitea/testdata/webhooks/release.json.golden
scm/driver/gitea/webhook.go
scm/driver/gitea/webhook_test.go
scm/driver/github/release.go
scm/driver/github/testdata/release.json.golden
scm/driver/github/testdata/releases.json.golden
scm/driver/github/testdata/webhooks/release.json.golden
scm/driver/github/webhook.go
scm/driver/gitlab/testdata/webhooks/release.json
scm/driver/gitlab/testdata/webhooks/release.json.golden
scm/driver/gitlab/webhook.go
scm/driver/gitlab/webhook_test.go
scm/driver/gogs/release.go
scm/driver/gogs/testdata/webhooks/release.json
scm/driver/gogs/testdata/webhooks/release.json.golden
scm/driver/gogs/webhook.go
scm/driver/gogs/webhook_test.go
scm/pr.go
scm/release.go
scm/webhook.go

the release webhook payload was missing... the release
implemented for: github, gitlab, gitea and gogs

fix: release webhook support

---

scm/driver/gitea/repo.go
scm/driver/gitea/repo_test.go
scm/driver/github/repo.go
scm/driver/github/repo_test.go
scm/driver/gitlab/repo.go
scm/driver/gogs/repo.go
scm/driver/gogs/repo_test.go
scm/repo.go

add the ability to create webhooks for 'release' events
implemented for: github, gitlab, gitea, gogs

feat: create hooks with release events

---

scm/client.go
scm/factory/factory.go

BitBucket Cloud OAuth flow was boken for a number of reasons.
Now, with the use of an env variable, we can request an AccessToken
from BB, and then use that for Bearer authentication against BitBuckets
API.

fix: bitbucket oauth flow fixed

---

scm/driver/bitbucket/org.go
scm/driver/bitbucket/pr.go
scm/driver/bitbucket/testdata/pr_create.json
scm/driver/bitbucket/testdata/pr_create.json.golden
scm/driver/bitbucket/testdata/pulls.json
scm/driver/bitbucket/testdata/pulls.json.golden
scm/driver/bitbucket/webhook.go

Enhance bitbucket cloud support in jenkins-x.
* Supports handling of PR comment in bitbucket cloud
* Enables submitting ChatOps commands such as "/retest" on a PR that triggers a pipeline run
Verification of the changes has been done manually

feat: Bitbucket cloud PR comment support

---

scm/driver/bitbucket/pr.go
scm/driver/bitbucket/repo.go
scm/driver/bitbucket/testdata/pr_create.json.golden
scm/driver/bitbucket/testdata/pulls.json.golden
scm/driver/bitbucket/user.go
scm/driver/bitbucket/webhook.go

Fix bitbucket.IsCollaborator and streamline initialisation of Login attribute value
* check repo permission for a user using account id instead of username since bitbucket clould 2.0 API has stopped using username in the API.
* initialise Login attribute with AccountId since  bitbucket clould 2.0 API responses do not include username in the result

Fix Bitbucket IsCollaborator api

---

scm/driver/github/review.go

The API doesn't like it when fields like `comments` or `commit_id` are there but empty or null. If they're not set, it's best to omit them entirely.

fix: add omitempty

---

scm/driver/bitbucket/git.go
scm/driver/bitbucket/testdata/webhooks/pr_created_slashbranch.json
scm/driver/bitbucket/testdata/webhooks/pr_created_slashbranch.json.golden
scm/driver/bitbucket/webhook_test.go

Fetching Sha of a branch (ref) with "/" in the name (e.g. foo/bar) returned "bar" incorrectly instead of its sha in case of BBC.
This caused the pipeline execution to fail.

fix: error fetching sha for branch name with slash in it

---

scm/driver/fake/pr.go
scm/driver/fake/pr_test.go

The fake driver did not respond to PullRequestListOptions
Most are implemented here.
Handling of opts.Labels is not implemented.

fix: fake pull request list handles most opts

---

scm/client.go
scm/driver/gitlab/util.go
scm/driver/gitlab/util_test.go

Fix the order of getting comments in gitlab.
In order to correctly obtain the variables in PR。
After the new version is released, I will create a new PR on https://github.com/jenkins-x-plugins/jx-gitops。

fix: add Sort option

---

scm/driver/azure/webhook.go
scm/driver/github/issue.go
scm/driver/github/issue_test.go
scm/driver/github/testdata/issue_search.json.golden
scm/driver/github/testdata/webhooks/issue_comment.json.golden
scm/driver/github/webhook_test.go
scm/issue.go
scm/webhook.go

fix: fix failing lighthouse builds

---

scm/driver/gitlab/testdata/webhooks/pull_request_comment_create.json
scm/driver/gitlab/testdata/webhooks/pull_request_edited.json
scm/driver/gitlab/testdata/webhooks/pull_request_reopen.json
scm/driver/gitlab/webhook.go

Gitlab MergeRequestHook have unstable json type for this property. https://gitlab.com/gitlab-org/gitlab/-/issues/15647
closes jenkins-x/go-scm#300

fix: flanky force_remove_source_branch type

---

scm/driver/fake/pr.go

Since filtering on labels is lacing on other providers I don't see that the fake should fail on that. A couple of more fields to be able to create tests for reuse of pull requests.
This is needed to make the tests in jenkins-x-plugins/jx-promote#412 work

feat: Improvements on fake

---

scm/driver/gitlab/repo.go
scm/driver/gitlab/repo_test.go
scm/driver/gitlab/testdata/merge.json.golden
scm/driver/gitlab/testdata/merges.json.golden
scm/driver/gitlab/testdata/nested_repo.json
scm/driver/gitlab/testdata/nested_repo.json.golden
scm/driver/gitlab/testdata/pr_create.json.golden
scm/driver/gitlab/testdata/repo.json.golden
scm/driver/gitlab/testdata/repos.json.golden

Not handling updated time, as gitlab only returns last_activity_time which does not have the same meaning.

Correctly populate the creation time of a gitlab repository.

---

go.mod
go.sum

A [previous dependabot change](https://github.com/jenkins-x/go-scm/pull/378) bumped this to a beta release candidate. This downgrades the depencency to the latest released version - v0.26.3.

Downgrade k8s.io/apimachinery to v0.26.3 (latest)

---

scm/driver/bitbucket/repo_test.go
scm/driver/bitbucket/testdata/repo-permision.json
scm/driver/bitbucket/testdata/repo-permision.json.golden
scm/driver/bitbucket/user.go

Since Bitbucket has removed the username field, the 'login' field need to be mapped with the user ID instead. Prior to this change, calling ListCollaborators would return:
```
{
Login: "",
Name:  "johndoe",
Avatar: "https://bitbucket.org/account//avatar/32/"
}
```
After change:
```
{
Login: "5c9078461b780c2c5d7bac4c",
Name:  "johndoe",
Avatar: "https://bitbucket.org/account/5c9078461b780c2c5d7bac4c/avatar/32/"
}
```
this causes all approvers being filtered and return empty owner result. see:
https://github.com/jenkins-x/lighthouse/blob/main/pkg/repoowners/repoowners.go#L293

fix login field value missing on bitbucket cloud

---

scm/driver/gitlab/testdata/webhooks/branch_create.json.golden
scm/driver/gitlab/testdata/webhooks/push.json.golden
scm/driver/gitlab/testdata/webhooks/push2.json.golden
scm/driver/gitlab/testdata/webhooks/tag_create.json.golden
scm/driver/gitlab/webhook.go
scm/factory/examples/repo/main.go

When convert a push webhook from gitlab, Commits field is missing.

fix：gitlab push hook, add pushCommits field

---

scm/driver/gitlab/repo.go

Fixing AddCollaborator to tell when a user is already a member:
- response 409 Conflict signals user having already been a member
GitLab doesn't implement the invite/accept workflow:
- successfully adding a member also reports it as being a member
This is to prevent client code continuing with the invite/accept workflow after calling AddCollaborator.
E.g. https://github.com/jenkins-x-plugins/jx-project/pull/454

gitlab: AddCollaborator tell when user is a member

---

.github/workflows/pull-request.yaml

Testing (running `go test ./...`) with go 1.18 fails with message
```
../../../go/pkg/mod/github.com/go-git/go-git/v5@v5.11.0/utils/trace/trace.go:15:17: undefined: atomic.Int32
note: module requires Go 1.19
```
Testing with go 1.21 or 1.22 fails with the message:
```
go: updates to go.mod needed; to update it:
go mod tidy
```
Running `go mod tidy -go=1.19` yields:
```
go: k8s.io/apimachinery@v0.29.0 requires go@1.21, but 1.19 is requested
```
Running `go mod tidy` without specifying the version bumps the go version and go toolchain version. Running `make lint` after this causes a panic.
This PR simply bumps the go version for running tests to 1.20 to enable unrelated changes to be merged.

Bump version of golang used for testing

---

scm/driver/github/testdata/webhooks/pr_closed.json.golden
scm/driver/github/testdata/webhooks/pr_edited.json.golden
scm/driver/github/testdata/webhooks/pr_labeled.json.golden
scm/driver/github/testdata/webhooks/pr_unlabeled.json.golden
scm/pr.go

This method is used to in (among others) the code for GitHub when interpreting the value of `mergeable_state` as returned by the rest API. But it seems like the code is based on the possible values of the field [MergeableState](https://docs.github.com/en/graphql/reference/enums#mergeablestate) in the GraphQL API. But based on the community discussions listed below the possible values are actually the ones listed for [MergeStateStatus](https://docs.github.com/en/graphql/reference/enums#mergestatestatus) in the GraphQL API.
https://github.com/orgs/community/discussions/24299#discussioncomment-3243704
https://github.com/orgs/community/discussions/21886

fix: add github api value for conflict

---

scm/driver/github/release.go

I noticed that new releases of jx don't get the badge **Latest**. That should be done by https://github.com/jenkins-x/jx3-versions/blob/master/.lighthouse/jenkins-x/release.yaml#L46, but it currently only remove the **Pre-release** badge. (I have added the **Latest** badge manually.) After debugging the http requests I noticed that adding make_latest=true does add the **Latest** badge. That also conforms with the current documentation. I can't find any information from GitHub about this API change though.

fix: github now requires explicit make_latest=true on update

---

scm/driver/stash/git.go
scm/driver/stash/testdata/changes.json.golden
scm/driver/stash/testdata/pr_change.json.golden
scm/pr.go

file's modification status is missing in response of Pull Request changes and commit changes APIs. this PR addresses that issue in Bitbucket server (stash).

Add modifiy field in changes APIs in Bitbucket server (stash)

---

scm/driver/stash/content.go
scm/driver/stash/content_test.go
scm/driver/stash/multipart.go
scm/driver/stash/stash.go
scm/driver/stash/testdata/content_create.json

for Bitbucket Server (Stash) [content add](https://developer.atlassian.com/server/bitbucket/rest/v903/api-group-repository/#api-api-latest-projects-projectkey-repos-repositoryslug-browse-path-put) endpoint wasn't implemented before, this adds the endpoint and unit test for it.

Implement Content Add Endpoint for Bitbucket Server (stash)

---

scm/content.go
scm/driver/azure/content.go
scm/driver/azure/content_test.go
scm/driver/azure/integration/content_test.go
scm/driver/bitbucket/content.go
scm/driver/fake/content.go
scm/driver/fake/content_test.go
scm/driver/gitea/content.go
scm/driver/gitea/content_test.go
scm/driver/github/content.go
scm/driver/github/content_test.go
scm/driver/gitlab/content.go
scm/driver/gitlab/content_test.go
scm/driver/gogs/content.go
scm/driver/stash/content.go
scm/driver/stash/content_test.go
scm/driver/stash/testdata/content_list.json
scm/factory/examples/contentlist/main.go

[Content List](https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#idm8297638624) endpoint in Bitbucket server lists the content of a directory recusively, this PR implements it.

Implement Content List Endpoint for Bitbucket Server (stash)

---

scm/driver/stash/git.go
scm/driver/stash/git_test.go
scm/driver/stash/testdata/create_ref.json
scm/driver/stash/testdata/create_ref.json.golden

implements create ref endpoint which is intended for create branch in git service of Bitbucket server (stash).

Implement CreateRef Endpoint in Git Service for Bitbucket Server (stash)

---

scm/driver/stash/repo.go
scm/driver/stash/repo_test.go
scm/driver/stash/testdata/default_branch.json
scm/repo.go

fetched default branch for a repository because the default branch name may differ across repositories. [drone/go-scm](https://github.com/drone/go-scm/) also [does](https://github.com/drone/go-scm/blob/d9147fbe059d891b3bdb77adf8f2cd6f7044d427/scm/driver/stash/repo.go#L109) the same.

Fetch Default Branch for a Repository in Find Repository Endpoint for Bitbucket Server (stash)

---

scm/driver/stash/git.go
scm/driver/stash/git_test.go

implemented delete ref endpoint in git service for Bitbucket server.

Implement Delete Ref Endpoint in Git Service for Bitbucket Server (stash)

---

scm/driver/azure/pr.go
scm/driver/bitbucket/pr.go
scm/driver/fake/pr.go
scm/driver/gitea/pr.go
scm/driver/github/pr.go
scm/driver/gitlab/pr.go
scm/driver/gogs/pr.go
scm/driver/stash/pr.go
scm/driver/stash/pr_test.go
scm/pr.go

In Bitbucket server it is allowed to delete a pull request, this PR implements that [endpoint](https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#idm8287244352).

Implement Delete Pull Request Endpoint in Bitbucket Server (stash)

---

scm/driver/azure/git.go
scm/driver/bitbucket/git.go
scm/driver/bitbucket/git_test.go
scm/driver/fake/git.go
scm/driver/gitea/git.go
scm/driver/gitea/git_test.go
scm/driver/github/git.go
scm/driver/github/git_test.go
scm/driver/gitlab/git.go
scm/driver/gitlab/git_test.go
scm/driver/gogs/git.go
scm/driver/gogs/git_test.go
scm/driver/stash/git.go
scm/driver/stash/git_test.go
scm/driver/stash/testdata/default_branch.json.golden
scm/git.go

Users should be able to fetch Default branch for a repository. This PR implements GetDefaultBranch for following git providers:

Add GetDefaultBranch Endpoint in Git Service
